table V_FACT_FB_OPS_BSO
	lineageTag: 387e590f-f4e5-4f1e-a276-72e9d7849c09

	column BusinessUnit
		dataType: string
		lineageTag: 2e634f32-3605-428c-bd49-8a423b82f338
		summarizeBy: none
		sourceColumn: BusinessUnit

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d866b5b2-80a0-4dc7-a99a-1832e95bcc6a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 3aa28a09-9197-4583-b543-c22a2fd640cf
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column SalesOffice
		dataType: string
		lineageTag: 65fc1675-f8f1-42a7-9758-81358d1748b3
		summarizeBy: none
		sourceColumn: SalesOffice

		annotation SummarizationSetBy = Automatic

	column ProfitCenter
		dataType: string
		lineageTag: 798a3017-8e2a-4615-b99e-460733b23324
		summarizeBy: none
		sourceColumn: ProfitCenter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: double
		lineageTag: 92909644-c943-494a-ab98-9e29c4ec91a5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: string
		lineageTag: 49005d4d-8a0c-41a0-a31e-a3fa3f3b0acb
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column OBSODollars
		dataType: double
		lineageTag: f74ef007-80fe-45ad-b54e-2d934536adfe
		summarizeBy: sum
		sourceColumn: OBSODollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ActualVolume
		dataType: double
		lineageTag: 0979d840-c738-4774-aa23-e56ee2434a73
		summarizeBy: sum
		sourceColumn: ActualVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlanOBSODollars
		dataType: double
		lineageTag: 1caeb23c-cc26-4bfc-a974-dc0110f3d8df
		summarizeBy: sum
		sourceColumn: PlanOBSODollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlanVolume
		dataType: double
		lineageTag: 47cb3fb3-2173-4890-884e-8005ef7d341a
		summarizeBy: sum
		sourceColumn: PlanVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FcstOBSODollars
		dataType: double
		lineageTag: 676425af-20c8-4a1f-affd-50bc4eeaff83
		summarizeBy: sum
		sourceColumn: FcstOBSODollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FcstVolume
		dataType: double
		lineageTag: 38a6719d-a68e-4755-9468-e5c4ca5547ea
		summarizeBy: sum
		sourceColumn: FcstVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShrinkDollars
		dataType: double
		lineageTag: 86811e04-adff-4fbf-b848-a0222593b5f9
		summarizeBy: sum
		sourceColumn: ShrinkDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlanShrinkDollars
		dataType: double
		lineageTag: eda09a13-8021-484e-a99e-06aabbfb14d9
		summarizeBy: sum
		sourceColumn: PlanShrinkDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FcstShrinkDollars
		dataType: double
		lineageTag: 2a64b3f3-d7ab-435c-8677-8ab5276863fc
		summarizeBy: sum
		sourceColumn: FcstShrinkDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TradeBreakDollars
		dataType: double
		lineageTag: 08601185-b093-4501-ad92-b526475949ad
		summarizeBy: sum
		sourceColumn: TradeBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlanTradeBreakDollars
		dataType: double
		lineageTag: e1675d3f-86d5-47b3-9cb7-40b0ab258788
		summarizeBy: sum
		sourceColumn: PlanTradeBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FcstTradeBreakDollars
		dataType: double
		lineageTag: 5c9ca827-a22c-4935-8446-96d3ceb11f55
		summarizeBy: sum
		sourceColumn: FcstTradeBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WhseBreakDollars
		dataType: double
		lineageTag: 6e3ccf78-35a2-4836-b8c8-527bac5e8448
		summarizeBy: sum
		sourceColumn: WhseBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlanWhseBreakDollars
		dataType: double
		lineageTag: 8ecaea94-2882-44bb-9eed-49e96e365afc
		summarizeBy: sum
		sourceColumn: PlanWhseBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FcstWhseBreakDollars
		dataType: double
		lineageTag: 4813166d-413b-4631-b821-022272bf6ee8
		summarizeBy: sum
		sourceColumn: FcstWhseBreakDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthID = CONCATENATE(V_FACT_FB_OPS_BSO[Year],V_FACT_FB_OPS_BSO[Month])
		lineageTag: d1b54a47-a6d0-40c5-9330-f0821df02d68
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: 9cd959c6-0168-4fb6-bc57-735d0678bbd5
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column RC_BSO = COUNTROWS(V_FACT_FB_OPS_BSO)
		formatString: 0
		lineageTag: 44dd0b0b-1e46-4e6e-8057-d91d343d59e6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition V_FACT_FB_OPS_BSO = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(#"Snowflake Server",#"Snowflake Warehouse",[Implementation="2.0"]),
				    SOLUTIONS_DEV_Database = Source{[Name=Snowflake_DataBase,Kind="Database"]}[Data],
				    DSD_Schema = SOLUTIONS_DEV_Database{[Name=Snowflake_Schema,Kind="Schema"]}[Data],
				    Fact = DSD_Schema{[Name="V_Fact_FB_Ops_BSO",Kind="View"]}[Data],
					Filtered = Table.SelectRows(Fact, each #date([Year], Number.FromText([Month]), 1) >= Range_Start
				        and #date([Year], Number.FromText([Month]), 1) <= Range_End)
				in
				    Filtered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

