// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

EVALUATE
SUMMARIZECOLUMNS(
    Operation_Cal_Day[DayDate],
    "CY", CALCULATE([Volume_TL], V_Fact_FB_ToplineActuals_Summary[TimeGranularity] = "Monthly"),
    "YA", CALCULATE([Volume_TL],
        V_Fact_FB_ToplineActuals_Summary[TimeGranularity] = "Monthly",
        DATEADD(Operation_Cal_Day[DayDate], -1, YEAR)
    )
)
ORDER BY Operation_Cal_Day[DayDate] DESC
